apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include "labels.standard" . | nindent 4 }}
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels: {{ include "labels.standard" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels: {{ include "labels.standard" . | nindent 8 }}
    spec:
      containers:
        - name: response-js
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:  
              path: /health
              port: {{ .Values.env.PORT | default "3000" }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.env.PORT | default "3000" }}
          {{- with .Values.env }}
          env: 
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end -}}
          {{ end }}
          ports:
            - containerPort: {{ .Values.env.PORT | default "3000" }}
              name: http
              protocol: TCP
          resources: {{ toYaml .Values.resources | nindent 12 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
